### ISSUE TITLE
Heroku deployments not working 

### ISSUE THREAD

**Issue by charmas3r** [saleor/react-storefront#107]
`remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=14.0.0
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version >=14.0.0...
remote:        Downloading and installing node 17.3.0...
remote:        Using default npm version: 8.3.0
remote:        
remote: -----> Restoring cache
remote:        Caching has been disabled because NODE_MODULES_CACHE=false
remote:        
remote: -----> Installing dependencies
remote:        Installing node modules (package.json)
remote:        npm ERR! code ERESOLVE
remote:        npm ERR! ERESOLVE unable to resolve dependency tree
remote:        npm ERR! 
remote:        npm ERR! While resolving: react-storefront@0.1.0
remote:        npm ERR! Found: graphql@16.1.0
remote:        npm ERR! node_modules/graphql
remote:        npm ERR!   graphql@"16.1.0" from the root project
remote:        npm ERR!   peer graphql@"^14.0.0 || ^15.0.0 || ^16.0.0" from @apollo/client@3.5.6
remote:        npm ERR!   node_modules/@apollo/client
remote:        npm ERR!     @apollo/client@"3.5.6" from the root project
remote:        npm ERR!     peer @apollo/client@"^3.3.19" from @saleor/sdk@0.4.
remote:        npm ERR!     node_modules/@saleor/sdk
remote:        npm ERR!       @saleor/sdk@"^0.4.0" from the root project
remote:        npm ERR!   1 more (subscriptions-transport-ws)
remote:        npm ERR! 
remote:        npm ERR! Could not resolve dependency:
remote:        npm ERR! peer graphql@"^15.5.0" from @saleor/sdk@0.4.1
remote:        npm ERR! node_modules/@saleor/sdk
remote:        npm ERR!   @saleor/sdk@"^0.4.0" from the root project
remote:        npm ERR! 
remote:        npm ERR! Fix the upstream dependency conflict, or retry
remote:        npm ERR! this command with --force, or --legacy-peer-deps
remote:        npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
remote:        npm ERR! 
remote:        npm ERR! See /tmp/npmcache.VVj01/eresolve-report.txt for a full report.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.VVj01/_logs/2021-12-30T22_19_03_315Z-debug-0.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - Dangerous semver range (>) in engines.node
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile React.js (create-react-app) multi app.
remote: 
remote:  !     Push failed`

Fix: Add npm version to `package.json`:
`  "engines": {
    "node": ">=14 <15",
    "npm": ">=6.11.0 <7"
  },`

**Comment by zaiste** [comment]
Thanks! we added a section to our README. 

Heroku uses LTS versions. You can probably widen your range to include `v16` too. 

We won't be adding it directly to the repository as we target the latest Node.js version.
