### ISSUE TITLE
Lighthouse Report shows very poor perfomance

### ISSUE THREAD

**Issue by MikkelScheike** [saleor/react-storefront#144]
### Summary

It looks like Google's Lighthouse tool does not think the site is fast (at all).
I think it would be worthwhile to go through the findings and identify the problems or potential false flags. As of now, I would fear that as a user of the site (just by using the demo) my website would get slaughtered by Google for poor performance.
![image](https://user-images.githubusercontent.com/10270075/154292991-a8f82dad-1cde-4506-9d5c-56b4b81319bd.png)

The link to the report can be found [here](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fdemo.saleor.io%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)

### Steps to reproduce

Open Demo site
Run Lighhouse Report tool
See result

### What OS are you using?

Windows

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by mirekm** [comment]
Thanks, Mikkel. The stats come from the already deprecated, old `demo-storefront` https://github.com/saleor/saleor-storefront. We will soon update our page to feature our new, referential storefront starter pack (from this very repository here called `react-storefront`). The goal is to provide something barebone, aimed for best performance, and productivity so you stay focused on the fun part of storefront/experience development. The current (barebone) preview can be found under https://reactstorefront.vercel.app/
