### ISSUE TITLE
Allow countries other than Poland in the billing and shipping addresses

### ISSUE THREAD

**Issue by rodolfojcj** [saleor/react-storefront#145]
### Summary

In the checkout page, when filling the billing and shipping addresses, I would expect to enter the details of an address in my country, but that fails.

The HTTP traffic in the web browser inspector shows that a GraphQL request to the operationName `CheckoutBillingAddressUpdate` that is related with the query `mutation CheckoutBillingAddressUpdate` is failing, returning an error saying that "_This value is not valid for the address_".

The cause seems to be that the storefront only allows addresses for Poland.

### Steps to reproduce

1. Deploy your own `Saleor react-storefront` instance, pointing to a working `Saleor API` instance.
2. From the storefront UI, add some products to the shopping cart.
3. Proceed to checkout.
4. For the billing address, fill an address that is not located in Poland.

**Comment by rodolfojcj** [comment]
As a workaround to allow addresses for a single country that is not Poland and a single region, for example Florida in the United States of America, I found that these source code changes are useful:

```
diff --git a/components/checkout/AddressForm.tsx b/components/checkout/AddressForm.tsx
index 20c817a..d9f2d5b 100644
--- a/components/checkout/AddressForm.tsx
+++ b/components/checkout/AddressForm.tsx
@@ -15,6 +15,7 @@ export interface AddressFormData {
   lastName: string;
   phone: string;
   country: CountryCode;
+  countryArea: string;
   streetAddress1: string;
   city: string;
   postalCode: string;
@@ -43,7 +44,9 @@ export const AddressForm = ({
       firstName: existingAddressData?.firstName || "",
       lastName: existingAddressData?.lastName || "",
       phone: existingAddressData?.phone || "",
-      country: "PL",
+      // country: "PL",
+      country: "US",
+      countryArea: "Florida",
       streetAddress1: existingAddressData?.streetAddress1 || "",
       city: existingAddressData?.city || "",
       postalCode: existingAddressData?.postalCode || "",
diff --git a/components/checkout/SavedAddressSelectionList.tsx b/components/checkout/SavedAddressSelectionList.tsx
index c6de761..ab59334 100644
--- a/components/checkout/SavedAddressSelectionList.tsx
+++ b/components/checkout/SavedAddressSelectionList.tsx
@@ -37,7 +37,9 @@ export const SavedAddressSelectionList = ({
       firstName: address?.firstName,
       lastName: address?.lastName,
       phone: address?.phone || "",
-      country: "PL",
+      // country: "PL",
+      country: "US",
+      countryArea: "Florida",
       streetAddress1: address.streetAddress1,
       city: address.city,
       postalCode: address.postalCode,
diff --git a/components/checkout/ShippingAddressSection.tsx b/components/checkout/ShippingAddressSection.tsx
index c7a3f79..08faa6e 100644
--- a/components/checkout/ShippingAddressSection.tsx
+++ b/components/checkout/ShippingAddressSection.tsx
@@ -45,7 +45,9 @@ export const ShippingAddressSection = ({
           firstName: billingAddress.firstName || "",
           lastName: billingAddress.lastName || "",
           phone: billingAddress.phone || "",
-          country: (billingAddress.country.code as CountryCode) || "PL",
+          // country: (billingAddress.country.code as CountryCode) || "PL",
+          country: (billingAddress.country.code as CountryCode) || "US",
+          countryArea: "Florida",
           streetAddress1: billingAddress.streetAddress1 || "",
           city: billingAddress.city || "",
           postalCode: billingAddress.postalCode || "",
```

Those changes are applied against the sources of commit `bfc51e8df112` of this repository.

**Comment by timuric** [comment]
@rodolfojcj we are in process of building a brand new checkout that would be production ready, therefore we are not currently improving current one. We are planning to release beta in a month from now, please stay tuned

**Comment by brightonmike** [comment]
@timuric do you have any further info on this? e.g. how would a new checkout integrate with this platform or is it directly a part of it?

**Comment by marqpdx** [comment]
@timuric thanks for the info. Do you know if the 3.1 branch has a working checkout?

We have an install due in 30 days and were hoping to use the 3.x version; is the 2.x version still usable?

Thanks!

**Comment by timuric** [comment]
@brightonmike it will be open source, and headless, business as usual, but it will heading towards production ready, with payment apps included. Stay tuned by signing up to our newsletter https://saleor.typeform.com/to/JTJK0Nou

@marqpdx I strongly advice you to pick 3.1 and meantime you can explore react-storefront as a boilerplate for checkout, or wait for a month or so for the beta of the new checkout

Btw you can also give a spin to our new free developer accounts in Saleor cloud (click signup) https://console.saleor.io/
