### ISSUE TITLE
Remove locale/channel from URLs

### ISSUE THREAD

**Issue by brightonmike** [saleor/react-storefront#151]
### Summary

Apologies if this falls more into feature request territory... but I don't want locale/channel in the URLs.

I've removed the folders and remove them from `lib/$path.ts` but this is causing issues.

What is the correct approach here?

### Steps to reproduce

1. Remove locale/channel folder
2. Amend paths in `lib/$path.ts`
3. Many links still include locale/channel

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by brightonmike** [comment]
We've sort of managed to get this working, but there's likely going to be some bugs.

Rough steps:

- Removed the folders and moved the files up to root level
- in `lib/paths.ts` remove `._channel(currentChannel.slug)._locale(locale)`
- Regenerate $paths file
- Remove the `redirects` method from Next config

Might be cool to have something documented in the readme so other folks know how they can change the URL structure. 

I think we're also possibly going to have some GraphQL request issues with our changes above we'll need to amend.

**Comment by timuric** [comment]
@brightonmike thanks for feedback, for routing related questions please refer to nextjs documentation https://nextjs.org/docs/routing/introduction
