### ISSUE TITLE
Registration page button type is wrong.

### ISSUE THREAD

**Issue by wileyknight** [saleor/react-storefront#187]
### Summary

Button type in register.tsx should be submit. Currently set to type button and does not allow users to register an account.

### Steps to reproduce

1. Go to register page.
2. Enter user registration information.
3. Try to submit the form.

### What OS are you using?

Windows

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by matteius** [comment]
Same issue.
