### ISSUE TITLE
Saving data from shipping or billing forms

### ISSUE THREAD

**Issue by wileyknight** [saleor/react-storefront#195]
### Summary

Saving information from the forms should request a new checkout object.

It doesn't seem like the use same shipping as billing button is working due to the data being unavailable. The checkout object after saving the billing address is still null.

### Steps to reproduce

1. Fill out the checkout billing address form and save.
2. Select the use same address as the billing button.
3. Console.logging the checkout object and the billingAddress show the address as null and returns nothing.

### What OS are you using?

Windows

**Comment by RyanTamulevicz** [comment]
In the appropriate files for each section, you can enable them by changing the buttons types to "submit". I'm not sure if this is currently intentional but it is how to fix this.

**Comment by wileyknight** [comment]
Thanks for the comment. I didn't really look into fixing it. I just really want to get momentum going on getting this fully functional. I've been waiting for 7 months to start using the new 3 version and I'm so frustrated this isn't farther along.

**Comment by RyanTamulevicz** [comment]
@wileyknight another thing I forgot though, it also needs a country and countryArea. For testing purposes, I just made them variables under the onSelectSavedAddress. 

They are working on the Saleor-Checkout which I am hoping is really good when they are a bit more along on that. The rest of this works fine in my opinion as a good starter pack which is what they say it is!
