### ISSUE TITLE
Checkout payment stripe form not displayed

### ISSUE THREAD

**Issue by Mesrar** [saleor/react-storefront#199]
### Summary

On checkout page the stripe form not displayed 

### Steps to reproduce

1. configue stripe on dashboard ( public key and secret key)
2. active stripe pluging for the default-channel
3. go to storefront check the stripe radio button 
4. nothing dispalyed

### What OS are you using?

Linux

### Your `next.config.js` file

const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

const apiURL = new URL(process.env.NEXT_PUBLIC_API_URI);
const allowedImageDomains = process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS
  ? process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS.split(",")
  : [];
const imageConversionFormats = process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS
  ? process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS.split(",")
  : [];

module.exports = withBundleAnalyzer({
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [apiURL.hostname, ...allowedImageDomains],
    formats: imageConversionFormats,
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "x-content-type-options",
            value: "nosniff",
          },
          { key: "x-xss-protection", value: "1" },
          { key: "x-frame-options", value: "DENY" },
          {
            key: "strict-transport-security",
            value: "max-age=31536000; includeSubDomains",
          },
        ],
      },
    ];
  },
  experimental: {
    reactRoot: true,
  },
});

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by simon-online** [comment]
Yes, this is also happening for me with the latest version of react-storefront.

It seems as though the Stripe form is not getting rendered in the browser (client side) which I believe it needs to for it to work.

**Comment by simon-online** [comment]
The Stripe form was getting rendered in the browser ok.

I was able to resolve this issue by updating the @stripe/react-stripe-js and @stripe/stripe-js packages to the latest version which were:

```
'@stripe/react-stripe-js': ^1.8.1
'@stripe/stripe-js': ^1.31.0
```

The original package versions from the latest react-storefront were:

```
'@stripe/react-stripe-js': ^1.7.0
'@stripe/stripe-js': ^1.26.0
```
