### ISSUE TITLE
.env variable for NEXT_PUBLIC_DEFAULT_CHANNEL=default-channel doesn't work

### ISSUE THREAD

**Issue by wileyknight** [saleor/react-storefront#202]
### Summary

Changing the .env value for NEXT_PUBLIC_DEFAULT_CHANNEL does not do anything. A quick search shows that value is never read.

### Steps to reproduce

1. Change the .env NEXT_PUBLIC_DEFAULT_CHANNEL to anything.
2. Start the server.

**Comment by tiendq** [comment]
Yes, this variable does nothing. It is hardcoded in lib/region.ts
