### ISSUE TITLE
`npm i` failed to install modules - looks like Python version incompatibility.

### ISSUE THREAD

**Issue by jiapei100** [saleor/react-storefront#232]
### Summary

`npm i` failed to install modules with the following **ERROR** messages:

```console
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'saleor-site@3.0.0-a.0',
npm WARN EBADENGINE   required: { node: '>=12 <15' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.10.0' }
npm WARN EBADENGINE }
npm WARN deprecated @types/schema-utils@2.4.0: This is a stub types definition. schema-utils provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/react-svg@5.0.0: This is a stub types definition. react-svg provides its own type definitions, so you don't need this installed.
npm WARN deprecated @types/nuka-carousel@4.4.6: This is a stub types definition. nuka-carousel provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated babel-plugin-react-intl@7.9.4: this package has been renamed to babel-plugin-formatjs
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated cli-ux@6.0.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated intl-messageformat-parser@6.1.2: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated intl-messageformat-parser@5.5.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated @formatjs/intl-utils@3.8.4: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated @sentry/apm@5.27.1: Please migrate to @sentry/tracing; see: https://www.npmjs.com/package/@sentry/apm
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path ....../node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /opt/node-v16.15.0-linux-x64/bin/node ....../node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/opt/node-v16.15.0-linux-x64/bin/node',
npm ERR! gyp verb cli   '....../node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (....../node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (....../node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (....../node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at ....../node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at ....../node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at ....../node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (....../node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (....../node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (....../node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at ....../node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at ....../node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at ....../node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-05-27T08_59_27_883Z-debug-0.log
```

### Steps to reproduce

I actually followed [https://github.com/saleor/saleor-storefront/blob/main/README.md](https://github.com/saleor/saleor-storefront/blob/main/README.md)

```console
➜  git clone https://github.com/mirumee/saleor-storefront.git
➜  cd saleor-storefront
➜  npm i
```

3 setups bring the above **ERROR** messages.

### A link to a reproduction repository

https://github.com/saleor/react-storefront

### What OS are you using?

Linux

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
const withPlugins = require("next-compose-plugins");
const { PHASE_DEVELOPMENT_SERVER } = require("next/constants");
const withOptimizedImages = require("next-optimized-images");
const withTM = require("next-transpile-modules")(["register-service-worker"]);

const withServiceWorkerConfig = require("./config/next/config.serviceWorker");
const withBaseConfig = require("./config/next/config.base");
const withDevConfig = require("./config/next/config.dev");
const withProdConfig = require("./config/next/config.prod");

module.exports = withPlugins(
  [
    [withOptimizedImages, { handleImages: ["jpeg", "png", "webp", "gif"] }],
    withTM,
    withBaseConfig,
    withServiceWorkerConfig,
    [withDevConfig, {}, [PHASE_DEVELOPMENT_SERVER]],
    [withProdConfig, {}, ["!" + PHASE_DEVELOPMENT_SERVER]],
  ],
  {
    async headers() {
      return [
        {
          source: "/(.*)",
          headers: [
            {
              key: "x-content-type-options",
              value: "nosniff",
            },
            { key: "x-xss-protection", value: "1" },
            { key: "x-frame-options", value: "DENY" },
            {
              key: "strict-transport-security",
              value: "max-age=31536000; includeSubDomains",
            },
          ],
        },
      ];
    },
  }
);
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```
Please refer to [pastebin](https://pastebin.com/wUsYskGJ)

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
N/A
```

</details>

**Comment by chrislais** [comment]
Please note: this project use the [pnpm](https://pnpm.io/) package manager. To install it, run:

npm install -g pnpm
Install dependencies:

pnpm i
Start the dev server:

pnpm dev
Storefront can be now accessed at http://localhost:3001/.

**Comment by chrislais** [comment]
> 

npm install -g pnpm@6.32.12

**Comment by jiapei100** [comment]
@wileyknight 
Well... I don't use Windows at all, at least 15 years...

**Comment by wileyknight** [comment]
It looks like you are running npm/pnpm commands on the saleor core backend. `saleor-site@3.0.0-a.0`. To install the backend you'll need to run the python scripts. Follow the documentation for a windows install, it's roughly the same instructions for linux as it is on windows, if you want to manually install. (not recommended for beginners) https://docs.saleor.io/docs/3.x/developer/installation/windows Otherwise, follow the instructions to install with docker containers and the saleor platform. Until you are very comfortable with how this system works I would not tackle a manual install. Use docker compose https://docs.saleor.io/docs/3.x/developer/installation

The storefront is a javascript application in React/Next.js and uses pnpm as a package manager instead of the more common npm. Download this repository react-storefront. There is no python code in the storefront.

**Comment by jiapei100** [comment]
Hi, @wileyknight 

I actually followed [https://github.com/saleor/saleor-storefront/blob/main/README.md](https://github.com/saleor/saleor-storefront/blob/main/README.md) . I really do **NOT** like to use a docker, that's why I didn't follow [https://docs.saleor.io/docs/3.x/developer/installation](https://docs.saleor.io/docs/3.x/developer/installation) .

So, is there a manual for **non-docker** installation??

**Comment by wileyknight** [comment]
[jiapei100](https://github.com/jiapei100)

Follow the windows manual installation. It's exactly the same installation instructions on linux. I would however check the saleor-platform repository https://github.com/saleor/saleor-platform/blob/main/docker-compose.yml  for the env variables you are going to want for saleor, saleor-dashboard and react-storefront.

To get the whole system running you are going to want to install saleor, saleor-dashboard and react-storefront.

For the first time running you are going to want to populate the database with dummy data.

You'll need to publish products to see them on the website. They will need to be in categories, have prices, and have available inventory stock this can be configured with variants. Spend some time getting to know the dashboard it looks very straightforward but it's more complex than it first appears.

To have the products show up on the react-storefront home page they will need to be added to the navbar. In the react-storefront example homepage the navbar menu is used as the collection of items to display on the homepage. In the dashboard you'll need to add categories to the "Configuration > Navigation > navbar". Add new items giving any name and then link them to the categories where the items you want displayed exist.

Alternatively, if you set your backend api to https://vercel.saleor.cloud/graphql/ this will let you see the dummy data. However, this will not reflect the data running locally. Your local backend api will be http://localhost:8000/graphql/

**Comment by wileyknight** [comment]
@jiapei100 

Close this thread. It's not a python problem in the react-storefront.

**Comment by jiapei100** [comment]
@wileyknight 

Hi, I actually created a storefront here: [https://longervision.saleor.cloud/](https://longervision.saleor.cloud/) . However, 

- from [https://longervision.saleor.cloud/dashboard/site-settings](https://longervision.saleor.cloud/dashboard/site-settings), **Company Information** wouldn't let me update and it *ALWAYS** complains that **Country: This field is required.** , even if I've already clearly selected **Canada**.

- on **Products** page, [https://longervision.saleor.cloud/dashboard/products/?asc=true&sort=name](https://longervision.saleor.cloud/dashboard/products/?asc=true&sort=name), **Create Product** wouldn't let me **Save**. The **Save** buton is **ALWAYS grayed out**.


That's why I started building everything from my own environment... 

So, for now, I've got to install **ALL**:
- **saleor**
- **saleor-dashboard**
- **react-storefront**
? Right?

**Comment by wileyknight** [comment]
@jiapei100

That's correct.

**Comment by jiapei100** [comment]
@wileyknight 

Still some questions:

1. In `saleor/tox.ini`, **python3.9** is there by default . But my python is of version **3.10**. Wondering if **python version** can be configured automatically? Instead of by specifying a FIXED version?
2. Is there a way to build **ALL** without **docker** ???

Thank you very much...

**Comment by wileyknight** [comment]
@jiapei100 

I am running python v 3.8.10 with no problems...

Running everything in a docker container is the recommended production way to deploy.

You can configure everything yourself using a proxy service and pointing to the running ports. Reference the docker-compose.yml file in the saleor platform to see the scripts used.

You don't need Jaeger or Mailhog to deploy. Everything else is standard to run and deploy.

If you are still having problems this might not be the best solution for you. This suite puts the developer first. It's very powerful but requires a fairly skilled developer to polish it off and deploy. You'll need to have a decent understanding node, next and react.

**Comment by jiapei100** [comment]
@wileyknight 

But, how to register my Email to from **local storefront** ? [http://localhost:3001/default-channel/en-US](http://localhost:3001/default-channel/en-US) , as well as **dashboard** ? [http://localhost:9000/](http://localhost:9000/)

**Comment by wileyknight** [comment]
@jiapei100 

There is a registration page on the storefront. You will probably have to change the button type from button to submit. I'm not sure if that was fixed yet.

You then need to set the user as active in the dashboard.

The storefront is a template. You need to put in a lot of work to finish it off. It's not a full turn-key solution. That's the beauty of using this store.

**Comment by jiapei100** [comment]
@wileyknight 

1. Where is the place I can replace `www.example.com` to `www.mywebsite.com` for ALL occurences?
2. How to deploy the built storefront to `www.mywebsite.com` hosting?

**Comment by wileyknight** [comment]
@jiapei100

You need to do your research. Learn how to host a node.js site. Your hosting company should be able to help. If you're self hosting than start learning nginx.

You shouldn't be trying to host this kind of solution if you don't know the basics. I've given you all the information you need. It's time to spend some time and get to understand the technology you want to use to become effective. It'll take months for a beginner to fully understand how this thing works. Read thru everything I've already told you and learn the tech.
