### ISSUE TITLE
Cart: Updating qty. permanently disables the field until reload.

### ISSUE THREAD

**Issue by wileyknight** [saleor/react-storefront#239]
### Summary

When you update the quantity field of items listed in the cart the fields become disabled and will not enable until the page is refreshed.

### Steps to reproduce

1. Add items to the cart.
2. Update the quantity.

**Comment by gtomaka** [comment]
I believe it is related to this issue: https://github.com/apollographql/apollo-client/issues/9602
In order to fix that you need to update Apollo Client. Simply run pnpm i @apollo/client@next and you should be fine :)
