### ISSUE TITLE
Navbar and footer menu in react-storefront does not change after changing language

### ISSUE THREAD

**Issue by denisdemolli** [saleor/react-storefront#252]
### Summary

Navbar and footer menu in react-storefront does not change after changing language. Everything except navbar and footer change the texts appropriately. But navbar and footer texts stay in English. They do not translate. I believe that multilingual e-commerce needs to translate completly. 

Was this bug solved and I am just using old version? I see this bug on official demo site as well as on my local machine.

### Steps to reproduce

Go to: https://reactstorefront.vercel.app/
Change language in the footer.
Look at the navbar and footer.

### What OS are you using?

Linux

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by timuric** [comment]
@denisdemolli unfortunately dashboard doesn't have UI for menu translations, but it is supported in the API
https://github.com/saleor/saleor-dashboard/issues/927

We will add it in the near future.

**Comment by denisdemolli** [comment]
Thanks for the information. By the way it seems the product description is not translating either. But I am looking forward for the fully multilingual Saleor. I guess you don't have any estimate about when it will be working?
Meanwhile it would be great and I would appreciate it a lot if you could advise me some quicky(hacky) way how I can make the navbar, footer and product description translatable? Thanks.

**Comment by denisdemolli** [comment]
Is it possible to create different storefronts (each with different language) and connect them to different channels? For example: Can I hardcode some storefront in English language and connect it to eng channel and another storefront in German language and connect it to the German channel. Does Saleor support different storefronts connected to the same backend(core)?

**Comment by timuric** [comment]
@denisdemolli yes, you could absolutely do it. Saleor is completely headless, you can use its API as you wish.

**Comment by denisdemolli** [comment]
Thanks. Is there any guide on how to connect multiple storefronts to 1 backend?
