### ISSUE TITLE
Invalid product price cached when switching channels in the dev mode

### ISSUE THREAD

**Issue by stnatic** [saleor/react-storefront#254]
### Summary

After a fresh pull from `main` and clicking some buttons I ended up in a state where the selected channel is USD, but the price displayed is in PLN:
![image](https://user-images.githubusercontent.com/2566928/173327432-206ebc11-fe38-44ec-927e-c496abb20d40.png)

The issue does not happen in the production build with just 2 channels, but I haven't tested it for more than 2 channels. 

It can be resolved by bypassing the apollo query cache (`fetchPolicy: "no-cache"`).

### Steps to reproduce

1. Run the dev server
2. Go to product details, e.g. the Saleor Beanie. 
3. Switch channel from `USD` to `PLN` several time

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by timuric** [comment]
@stnatic thanks for reporting, should be fixed now
