### ISSUE TITLE
In cart summary does not show the tax price

### ISSUE THREAD

**Issue by ianninirojas** [saleor/react-storefront#270]
### Summary

In cart summary does not reflect taxes, I want to show the taxes in the cart summary, but the product that I added hasn't the tax price.

Tax dashboard config
![tax-config](https://user-images.githubusercontent.com/9159029/179001880-92ff6df4-16c5-4859-8d1c-2f9cd31e57e5.png)

Cart summary
![cart-summary](https://user-images.githubusercontent.com/9159029/179003551-98800f24-053d-4285-98d8-0062cb0350b3.png)

Object checkout
![object-checkout](https://user-images.githubusercontent.com/9159029/179002614-2a4448ac-71f3-43c5-b581-673975c9c884.png)

### Steps to reproduce

1. Add the product to the cart
2. Go to cart summary
3. Do not show the tax price

### What OS are you using?

Mac OS

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

**Comment by serranomorante** [comment]
Did you manage to solve this?
