### ISSUE TITLE
Checkout: Signed in user required to login again. No feedback for a bad login attempt. 

### ISSUE THREAD

**Issue by wileyknight** [saleor/react-storefront#280]
When entering checkout from the react-storefront as a logged in user. The logged in user is required to sign in again.

There is no feedback for an unsuccessful login attempt.

**Comment by mmiszy** [comment]
Fixed now by introducing rewrites and serving storefront and checkout from the same domain:
https://github.com/saleor/react-storefront/issues/418
https://github.com/saleor/react-storefront/commit/c81cb41ba29734132b99e3c9d8b7b446d666d4ac
