### ISSUE TITLE
Add Stripe to payment providers

### ISSUE THREAD

**Issue by wileyknight** [saleor/react-storefront#281]
It doesn't appear that Stripe is currently a payment provider. I see support for Mollie and Adyen.

**Comment by mmiszy** [comment]
There's a Work In Progress PR here: https://github.com/saleor/react-storefront/pull/347
Stripe Payments should be ready for testing next week.

**Comment by wileyknight** [comment]
Is this going to be the full integration with the long form or is this going to be like the current integration with only the credit card field available?

**Comment by mmiszy** [comment]
As of now, we're integrating credit cards. We're planning to extend this in the future - it'll be a low hanging fruit once the first integration is done :)
