### ISSUE TITLE
how could i add/remove countries into shipping country list ?

### ISSUE THREAD

**Issue by blackyzero** [saleor/react-storefront#282]
Hello, 
How could i add/remove countries into shipping country list ? Currently, there are only 4 countries.

i also created a shipping zone, only assigned 1 country, but it still shows 4 countries in Shipping address section at checkout page.

Thank you.
<img width="756" alt="Screen-Shot-2022-06-05-at-9 58 44-AM" src="https://user-images.githubusercontent.com/4286063/172226471-e50ede1c-7a96-4474-80a1-ad36c2095f05.png">

**Comment by mmiszy** [comment]
Fixed via https://github.com/saleor/react-storefront/pull/558
