### ISSUE TITLE
Decide the future of `material-ui`

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#285]
Currently we're using `material-ui` packages in [packages/checkout-storefront](https://github.com/saleor/saleor-checkout/tree/main/packages/checkout-storefront). There are a few concerns:

- We're on version 4 which is not longer developed
- material-ui 4 forces us to use `getInitialProps` in Next.js which results in poor performance and limits our abilities to optimize

We should either upgrade to material-ui 5 (renamed to `@mui/material`) or drop it completely and replace with something else (what?).

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/macaw-ui/issues/157

**Comment by mmiszy** [comment]
It's been decided: https://github.com/saleor/macaw-ui/issues/157
RFC is in progress.
