### ISSUE TITLE
Use Vercel Build Output API in GitHub actions

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#309]
**Is your feature request related to a problem? Please describe.**
It's pretty annoying to wait for build of the project in GitHub Actions and wait again to make the same build in Vercel (usually stuck in queue due to lack of parallel builds).

**Describe the solution you'd like**
We could use the newly announced [Vercel Build Output API](https://vercel.com/blog/build-output-api) and `vercel deploy --prebuilt` comamnd to push the build artefacts from Next.js created in GitHub Actions directly to Vercel

**Describe alternatives you've considered**
Don't build the app in GitHub actions, as it's already done by Vercel (fail would be visible in PR).  However this doesn't help with builds stuck in queue.

**Comment by mmiszy** [comment]
I think we still need to build apps in GitHub Actions so that we can run other checks: `tsc`, `eslint` and `paths`
