### ISSUE TITLE
Remove MSW and fix Polly recordings

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#310]
# Requests made by payment provider SDKs are not recorded by Polly.js
### Case 1
1. Run test with `POLLY_MODE=record`, e.g. `POLLY_MODE=record pnpm run test`

### Case 2
1. Change values for `TEST_MOLLIE_KEY` to be invalid Mollie API key
2. Run tests in replay mode: `pnpm run test`

## Current result

Requests made by Mollie SDK are not recorded by Polly.js

In **case 1**: Requests made to Mollie SDK won't be saved in `/recordings`

In **case 2**: Requests will be made to the real Mollie SDK and fail because the API key is invalid.

## Expected behavior

All requests are intercepted by Polly.js and recorded.

#### System:
 - OS: macOS 12.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 118.25 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
#### Binaries:
 - Node: 18.2.0 - /usr/local/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.9.0 - /usr/local/bin/npm
 - Watchman: 2022.05.16.00 - /usr/local/bin/watchman
#### Browsers:
 - Brave Browser: 103.1.41.100
 - Chrome: 103.0.5060.134
 - Firefox Developer Edition: 101.0
 - Safari: 15.5

#### pnpm
- pnpm: 7.5.2

## Additional context

When I've changed Polly.js adapter in `test-utils.ts` to `@pollyjs/adapter-node-http` and harcoded responses from requests made to Saleor API (private app metadata) in `backend/payments/providers/mollie/utils.ts:15` the requests to Mollie API were intercepted properly by Polly.js.

However this breaks manual mocks for Saleor API - they are no longer handled and fail.

We might solve this by getting rid of msw and instead mocking functions that return make requests to retreive app's metadata from Saleor.

**Comment by mmiszy** [comment]
We need to get rid of MSW (Mock Service Worker) and revamp our tests setup.
