### ISSUE TITLE
Dummy payment gateway

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#338]
Add a dummy payment gateway to saleor-app-checkout.

This way you could complete the flow without setting up Mollie or Adyen and it would give you a baseline for writing your own integration

**Comment by rodolfojcj** [comment]
Hello @mmiszy.

I would like to have this implemented. Do you have an estimation for it?

On the other hand, I can help to implement it if someone gives me a hand with these:
- An overview of the work required.
- An overview of how the full implementation would be.
- The initial guidelines for starting.

Thank you.

**Comment by witoszekdev** [comment]
This feature was implemented in this PR: https://github.com/saleor/react-storefront/pull/484
