### ISSUE TITLE
Update demo environment

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#349]
- ~[ ] check on `demo-test`~
- [x] update `demo-staging`
- [x] update `demo`

**Comment by witoszekdev** [comment]
We shouldn't use `demo-test` anymore, and use `demo-staging` from old checkout repo 😅

**Comment by mmiszy** [comment]
Closed via https://github.com/saleor/react-storefront/commit/5a96d3964b85cf2bf0a0744cec40055706ca4209 https://github.com/saleor/react-storefront/commit/5a96d3964b85cf2bf0a0744cec40055706ca4209
