### ISSUE TITLE
Handle authenticated checkout

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#351]
## Problem

Right now, if a user signs into storefront with their account and adds items to a cart, we create a checkout session that is assigned to this specific user.

When we redirect user to checkout, which is hosted on a different domain (demo.saleor.io → checkout.demo.saleor.io) we no longer have session token to authenticate requests. This causes the query for that order to return `null` (not found).

We need to find a **secure** way of passing session tokens to checkout

## Possible solutions

- Pass `csrfToken` in URL, read `refreshToken` from cookie and regenerate `accessToken` using `tokenRefresh` mutation
  - ❌ Not secure
  - There's a risk of leaking `refreshToken` to 3rd parties
  - Cookies authentication is deprecated,  setting cookies for `refreshToken` shouldn't be handled by Saleor GrpahQL API
- Put checkout inside an `<iframe>` and pass tokens using `postMessage`
  - ❌ This makes it very hard to host one checkout for multiple storefronts
  - In order to prevent [clickjacking](https://owasp.org/www-community/attacks/Clickjacking), checkout would need to set `Content-Security-Policy: frame-ancestors` header with all domains that are allowed to include checkout as an `<iframe>`
- Add a new API for generating `accessToken` that's scoped only for completing checkout for that user
  - ❓ To be discussed further

**Comment by mmiszy** [comment]
Some research:

1. https://stackoverflow.com/a/66641039/704894
2. https://stackoverflow.com/a/37392811/704894
3. https://stackoverflow.com/a/39905960/704894
4. https://docs.oracle.com/cd/E24152_01/Platform.10-1/ATGPlatformProgGuide/html/s0906sharingasessionacrossmultipledom01.html#s0906sessionrecoverywithjavascript01

More to follow

**Comment by timuric** [comment]
@witoszekdev Is there a known use case of hosting checkout on a different domain than storefront?

**Comment by mmiszy** [comment]
@timuric  Even our demos do that. This issue was created from a long discussion with @patrys

**Comment by mmiszy** [comment]
We can fix the issue in demo environment by rewriting checkout URL into a subpath. See https://github.com/vercel/next.js/blob/canary/examples/with-zones/home/next.config.js

**Comment by mmiszy** [comment]
We've fixed this problem in demo here: https://github.com/saleor/react-storefront/issues/418
