### ISSUE TITLE
Handle user selecting address with different country than checkout default country

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#365]
Currently we pass countryCode do checkout in the url, so we setup delivery methods based on that country right away. Vast majority of users will buy at e.g polish store when planning to ship to polish address. Problem is when user shops at a polish store, then only in checkout select e.g french shipping address. What happens is that the delivery methods remain outdated until all the updates  from api are applied to checkout and may cause error if user selects the outdated method before the state updates. It's an edge case, but we should find a solution to make that better.

**Comment by timuric** [comment]
Changing country could discard selected shipping method option and apply default one for France
