### ISSUE TITLE
Missing OG image / social media images

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#369]
Add missing OG image and / or other social media images to the storefront.

**Comment by AGrant24** [comment]
Hi, which images are missing? both of these show up on Discord and Whatsapp



![Image](https://user-images.githubusercontent.com/30240265/183726747-5cdf28c3-39da-46ba-8d9a-d2210e57efb2.png)

**Comment by mmiszy** [comment]
Yes, but they do not show on Facebook, Twitter or LinkedIn.

**Comment by AGrant24** [comment]
Okay, I will see what I can do
