### ISSUE TITLE
Add phone input to checkout

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#371]
- [x] Add phone number input to the Checkout flow.
- [x] Validate phone number.

In checkout designs there is a [nice phone input](https://www.figma.com/file/oBQhZFwyFcXauxFrb3mbRb/saleor_checkout?node-id=2482%3A11686). Let's implement it in ui-kit so it's more user friendly.

**Comment by mmiszy** [comment]
Let's use `libphonenumber` for validation.
