### ISSUE TITLE
Improve form inputs accessibility

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#375]
Our current form inputs aren't really accessible. Here's an action list on what we can improve:

- Link `<label>` with `<input>` by using `for=` attribute
- Link error messages with `<input>` by using `aria-describedby` attribute
- Mark input as invalid with `aria-invalid="true"`
- Render in DOM hidden form elements (e.g. billing address) so that it's always visible to screen reader users and to browser extensions
- Wrap our form in a `<form>` element, with each section distinguished with `<fieldset>`
  - This way we can handle form submission with `onSubmit` handler

**Comment by mmiszy** [comment]
Most of this was implemented in https://github.com/saleor/react-storefront/pull/328
