### ISSUE TITLE
Change pay button in checkout being disabled to always enabled with errors thrown if necessary

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#387]
Currently if some information is missing or incorrect in checkout the pay button is disabled, not providing much info to the user about the particular reason. It'd make more sense to always enable the button and in case some info is missing or incorrect before making request to the api throw alert saying what is wrong.

**Comment by mmiszy** [comment]
@bmigirl is this related https://github.com/saleor/react-storefront/issues/377 ?
