### ISSUE TITLE
Installed "checkout" third-party app gives runtime errors in the Dashboard

### ISSUE THREAD

**Issue by rodolfojcj** [saleor/react-storefront#388]
### Summary

I'm trying to follow the _Payment gateways configuration_ section of the README file for this repository, so that I can explore the configuration of the available payment methods. This is by going to _Apps > Third party apps > Checkout_.

But instead of getting a working page, I'm receiving three detailed **runtime errors**.

It's worth mentioning that I'm running the `react-storefront` Saleor project in a test server of mine. I'm not using any _vercel_ related stuff. In my test server I launch the local server with the `pnpm dev` command, which seems to be working fine. Also, I added the `checkout` third party app through the dashboard web UI, by visiting the _http://<YOUR_SALEOR_URL>/dashboard/apps/install?manifestUrl=<YOUR_MANIFEST_URL>_ link.

The [attached video](https://user-images.githubusercontent.com/458749/185039154-ef7fc072-d184-4dd9-ab39-44125d22c072.mp4) shows what I'm getting.

Am I missing something? Or is there a bug in some Saleor component (`core`, `dashboard`, `react-storefront`, etc)?

Thanks in advance for your attention and help.

### Steps to reproduce

1. In a Linux based server of yours, run the `react-storefront` project with the `pnpm dev` command.
2. Install the `checkout` third party app in the dashboard vis the _http://<YOUR_SALEOR_URL>/dashboard/apps/install?manifestUrl=<YOUR_MANIFEST_URL>_ link.
3. In the dashboard, follow the _Apps > Third party apps > Checkout_ menu sequence. Wait a little until the errors appear.

### Output from envinfo

7.9.0

**Comment by mmiszy** [comment]
The errors are:

> SecurityError: Failed to read the `localStorage` property from `Window`: access is denied for this document.

> Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

**Comment by mmiszy** [comment]
For the record, you should probably not be running `dev` on your production server. Instead, you should do `build` + `start`.

**Comment by rodolfojcj** [comment]
In a new try I observed that the reported error happens when the web browser is in "Incognito" or "Private" mode.

On the other hand, after trying with a non-private web browser session (on Firefox), I'm getting the expected working page for the added "Checkout" app, however there is still an error message in the web inspector console saying something like this:

    Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://198.58.107.209:3001') does not match the recipient window's origin ('http://dashboard.example.com').

It's worth mentioning that the Saleor setup I'm running uses plain HTTP and different domains and addresses, with something similar to these:

- dashboard.example.com, for the Saleor dashboard.
- api.example.com, for the Saleor API core.
- 198.58.107.209:3001 for the Saleor checkout app I'm trying to build, start and integrate with the previous two components.

Finally and for reference, these links may be useful:

- https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document/.
- https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
- https://javascript.info/cross-window-communication

**Comment by mmiszy** [comment]
Closing in favor of https://github.com/saleor/react-storefront/issues/599
