### ISSUE TITLE
Codesabdbox link is broken

### ISSUE THREAD

**Issue by timuric** [saleor/react-storefront#398]
### Summary

Codesandbox link in readme leads to a page with error:
```
Something went wrong
Only a max of 500 modules is allowed in a sandbox
```

### Steps to reproduce

Click in readme https://codesandbox.io/s/github/saleor/react-storefront

**Comment by mmiszy** [comment]
I guess the only thing we can do is removing this link for now.

https://github.com/codesandbox/codesandbox-client/issues/3229

> (…) hard limit on what can be used on CodeSandbox at the moment for performance reasons.

**Comment by mmiszy** [comment]
The link was removed in https://github.com/saleor/react-storefront/pull/396
