### ISSUE TITLE
Digital checkout

### ISSUE THREAD

**Issue by szczecha** [saleor/react-storefront#406]
For checkout with digital products only we don't add a shipping address so there is no reason to display the checkbox `use shipping as billing` 
![Zrzut ekranu 2022-08-22 o 12 12 03](https://user-images.githubusercontent.com/30683248/185898024-233db0ba-7753-4eb2-96e1-670cbb428916.png)

**Comment by mmiszy** [comment]
Verify if that's still a problem.
