### ISSUE TITLE
Authentication not Persisting

### ISSUE THREAD

**Issue by xydac** [saleor/react-storefront#41]
When I try to run this locally, Authentication doesn't seem to persist tab refresh.

Here's a screengrab showing the error-
![image](https://user-images.githubusercontent.com/422155/138171659-bb66d1e4-da4d-46c8-a6ac-c2e55db6258a.png)

It seems like authentication is not getting saved via the login api.

**Comment by xydac** [comment]
This is still an issue on latest main branch

**Comment by ianninirojas** [comment]
Hi! I have the same problem, the session does not persist after reloading the page. Did you find a solution?

**Comment by ianninirojas** [comment]
Hi  @mmiszy  thanks for answer. In [demo](https://demo.saleor.io/) you can't register/login, but my problem is that when I use this hook `const { login } = useAuth();` to log in, if someone refreshes the page the session disappears and the this `const { user, authenticated } = useAuthState();` is null

**Comment by ianninirojas** [comment]
someone could check this?

**Comment by peelar** [comment]
Hello @ianninirojas @wileyknight 👋 

Thanks for reaching out. We are looking into the potential causes of your issues, but we need your help to narrow them down.

Can you please provide us with steps to reproduce? We need all the details you can give us: how are you running Saleor, what is your environment, what configuration you are using, what version are you using, and whether it is modified or not.

Some potential causes may be:
1. Not having your frontend on the same origin as backend
2. Being behind a proxy or CDN (in which case you have to make sure all the headers and cookies are forwarded in both directions)

Are any of those possible in your setup?

**Comment by wileyknight** [comment]
I am running the storefront outside of the docker container but same server
