### ISSUE TITLE
Navigation is very slow.

### ISSUE THREAD

**Issue by endo-aki22** [saleor/react-storefront#414]
### Summary

The navigation to other pages is very slow. even it sometimes doesn't navigate or keeps loading infinitely.

https://user-images.githubusercontent.com/61251512/186481310-c5a911b7-23ff-49f8-8afc-b488c7a00baf.mp4

Also, In the Microsoft Edge browser, clicking on the product card doesn't navigate to the product page.

https://user-images.githubusercontent.com/61251512/186483503-1691a0ea-a664-4ae9-9b82-029a74eb46b5.mp4

### Steps to reproduce

Apparently, I guess there is an issue.

**Comment by mmiszy** [comment]
Thank you for reporting the problem!

The speed of navigating across subpages in local development is related to how fast your local builds work. Next.js refetches all the data on every navigation in local development. This is not the case in production mode.

We'll look into the Edge issue.
