### ISSUE TITLE
Add a `start` script at the parent monorepo level

### ISSUE THREAD

**Issue by rodolfojcj** [saleor/react-storefront#422]
### Summary

While being at the top level monorepo directory for `react-storefront`, it would be handy to run the `pnpm start` command to launch its `storefront` and `saleor-app-checkout` apps.

At this moment that command fails because such `start` script does not exist for the project.

This is with the `react-storefront` sources of commit ID `28ed7e53916e107fb25f837b5093787de0c97426`.

The ultimate goal of this requirement is to have a convenient way to execute the `next start` command defined by the `start` script inside the files `apps/storefront/package.json` and `apps/saleor-app-checkout/package.json`, which are suitable for a production mode.

### Steps to reproduce

1. Go to your local `react-storefront` directory.
2. Run `pnpm build` and wait for it to finish.
3. Run `pnpm start`.
4. An error output like the following is generated:
    > saleor-storefront@0.0.0 start /projects/react-storefront
    > node server.js
    node:internal/modules/cjs/loader:958
      throw err;
      ^
    Error: Cannot find module '/projects/react-storefront/server.js'
        at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
        at Module._load (node:internal/modules/cjs/loader:803:27)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:18:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }
    Node.js v18.8.0
     ELIFECYCLE  Command failed with exit code 1.

**Comment by peelar** [comment]
Hello @rodolfojcj 👋 

Thank you for your contribution. We will review the PR you submitted in the near time.
