### ISSUE TITLE
Error thrown when the Storefront is automatically launched by `saleor storefront create`

### ISSUE THREAD

**Issue by peelar** [saleor/react-storefront#444]
### Summary

After firing `saleor storefront create` and going through the wizard in the CLI, the apps should start automatically. However, they don’t because of an error below. When I kill the process and try to run pnpm dev manually, it boots up. 

![image](https://user-images.githubusercontent.com/44495184/188064138-e0698d46-0811-42dd-aa34-fc60e47267b9.png)

### Steps to reproduce

1. Use the `saleor storefront create` command to create a storefront
2. Go through the wizard
3. Wait for the installation to finish, and see it booting up

### Output from envinfo

```
## System:
 - OS: macOS 12.5.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 1.22 GB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.15.1 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.11.0 - /usr/local/bin/npm
## Browsers:
 - Chrome: 104.0.5112.101
 - Safari: 15.6.1
## pnpm: 7.5.0
```

**Comment by mmiszy** [comment]
@peelar can you verify if this is still the case?

**Comment by peelar** [comment]
@mmiszy Somehow I missed it. The flow has changed, and the dev server doesn't start automatically anymore. All good, you can close this one
