### ISSUE TITLE
Sign In Is not working

### ISSUE THREAD

**Issue by Farshid-997** [saleor/react-storefront#448]
### Summary

After the checkout while I am trying to sign in it is not sign in the page and give me an error - "credential did not match ". but my email and passwords are ok.

![Screenshot 2022-09-03 104803](https://user-images.githubusercontent.com/35967833/188256254-fa69d5d0-bb20-4d04-8313-385481fafa7d.png)

### Steps to reproduce

![Screenshot 2022-09-03 104803](https://user-images.githubusercontent.com/35967833/188256381-5ca455da-87a1-4120-85a5-8d54176ef9e4.png)

**Comment by timuric** [comment]
This looks like you are using a very old version, have you tried to checkout latest version from main?

**Comment by Farshid-997** [comment]
yes I implemented the latest version here but let me how can i check the version ?

**Comment by Farshid-997** [comment]
> This looks like you are using a very old version, have you tried to checkout latest version from main?

yes I implemented the latest version here but let me how can i check the version ?

**Comment by mmiszy** [comment]
@Farshid-997 what's your last entry in `git log`?
