### ISSUE TITLE
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: turbo run dev ...

### ISSUE THREAD

**Issue by jas02** [saleor/react-storefront#449]
### Summary

I have latest build of saleor-platform running in containers and container react-storefront is constantly failing with log message:

```
undefined

 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: turbo run dev --parallel --cache-dir=.turbo

spawn turbo ENOENT
```

### Steps to reproduce

Follow build instruction of saleor-platform using latest main branch, run `docker-compose up`, wait for containers to start. Container `saleor-platform_react-storefront` is failing.

## System:
 - OS: macOS 12.5
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 1.89 GB / 64.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 18.7.0 - /opt/homebrew/bin/node
 - npm: 8.15.0 - /opt/homebrew/bin/npm
## Browsers:
 - Chrome: 104.0.5112.101
 - Safari: 15.6
 
 pnpm --version
7.9.5

**Comment by peelar** [comment]
Hello @jas02 👋 

Is your `saleor-platform` freshly cloned or is it a repository that you upgraded submodules of? Because I can't reproduce it on a fresh install.
