### ISSUE TITLE
@sentry+cli Running install script, failed

### ISSUE THREAD

**Issue by slamer59** [saleor/react-storefront#459]
### Summary

From a clean clone, installing fails when installing **sentry**

### Steps to reproduce

1. git clone https://github.com/saleor/react-storefront
2. cd react-storefront
3. pnpm i

```
Scope: all 10 workspace projects
packages/ui-kit                          |  WARN  deprecated stable@0.1.8
apps/checkout                            |  WARN  deprecated source-map-resolve@0.6.0
apps/checkout                            |  WARN  deprecated svgo@1.3.2
packages/ui-kit                          |  WARN  deprecated sane@4.1.0
packages/ui-kit                          |  WARN  deprecated chokidar@2.1.8
packages/ui-kit                          |  WARN  deprecated fsevents@1.2.13
apps/saleor-app-checkout                 |  WARN  deprecated source-map-resolve@0.5.3
packages/ui-kit                          |  WARN  deprecated querystring@0.2.0
apps/saleor-app-checkout                 |  WARN  deprecated resolve-url@0.2.1
apps/saleor-app-checkout                 |  WARN  deprecated source-map-url@0.4.1
apps/saleor-app-checkout                 |  WARN  deprecated urix@0.1.0
packages/ui-kit                          |  WARN  deprecated uuid@3.4.0
Packages: +2786
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /media/thomas/DATA/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 2785, reused 2717, downloaded 0, added 2786, done
node_modules/.pnpm/@sentry+cli@1.74.5/node_modules/@sentry/cli: Running install script, failed in 218ms
.../node_modules/@sentry/cli install$ node ./scripts/install.js
└─ Failed in 218ms
node_modules/.pnpm/msw@0.43.1_typescript@4.7.4/node_modules/msw: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 1.
```

## System:
 - OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Memory: 9.21 GB / 15.59 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Browsers:
 - Firefox: 104.0

pnpm version : 7.9.3

**Comment by mmiszy** [comment]
Thank you for reporting this! Unfortunately, I'm having a hard time reproducing the problem :( It all seems to work for me locally and on Vercel.
However, I've seen some similar issues in the Sentry repository – do you think it would be appropriate to report it to them?

- https://github.com/getsentry/sentry-cli/issues/1308
- https://github.com/getsentry/sentry-cli/issues/1249
- https://github.com/getsentry/sentry-cli/issues/1226
- https://github.com/getsentry/sentry-cli/issues/1089

**Comment by slamer59** [comment]
Yes. I think it is something related to my environment. But it is still needed to understand. I will check.

**Comment by slamer59** [comment]
I think I understood the problem. 
the path of the cli is wrong 
`.../node_modules/@sentry/cli`

when it should be 
`node_modules/.pnpm/@sentry+cli@1.74.5/node_modules/@sentry/cli` 

pnpm seems to mess it up. I can install it manually. I don't know much pnpm and cannot find a workaround. 
Maybe push a message to sentry/pnpm team.

**Comment by slamer59** [comment]
It solve itself by magic... after installing node version 16 ? With SENTRYCLI_USE_LOCAL=1 ? I don't know... It feels like a sentry/cli bug. 

I will reopen if I am facing again this issue.
