### ISSUE TITLE
"Deploy to Vercel" button doesn't work

### ISSUE THREAD

**Issue by lkostrowski** [saleor/react-storefront#466]
### Summary

In readme (https://github.com/saleor/react-storefront/tree/canary/apps/storefront#vercel--netlify) there is a button that should automatically clone and deploy storefront to Vercel.

However, this doesn't work. At the moment, it fails on PNPM, but AFAIK it will continue failing, because "button" is constructing a query that doesn't work for monorepo

Here is Vercel reference https://vercel.com/docs/deploy-button

That provides configuration like build & install script and root directory.

### Steps to reproduce

1. Open docs - https://github.com/saleor/react-storefront/tree/canary/apps/storefront#vercel--netlify
2. Click Deploy to Vercel button
3. Proceed with Vercel deployment until build fails

**Comment by lkostrowski** [comment]
@mmiszy This is not closed via #469. This PR enabled next config, but it has to be configured for workspaces. You can try - it fails

**Comment by mmiszy** [comment]
Thanks @lkostrowski
