### ISSUE TITLE
Discuss possible replacements for react hook form

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#475]
As the checkout is growing in complexity and we're seeing more clearly where it's going, it becomes more evident that react hook form could be replaced with some more appropriate alternative (maybe formik?). We should discuss possible options

**Comment by mmiszy** [comment]
One of the pains is the lack of input-level async validation. `react-hook-form` only supports form validation.

**Comment by mmiszy** [comment]
Look at open source products, not just articles 🙃

**Comment by bmigirl** [comment]
We found that currently react hook form causes us problems:
- validation is not as good as expected, our validation resolver does the job but we cannot validate only part of the form or override that validation on field level
- we cannot set form errors in batch and had to write our own util using forEach (not a big issue but could be something out of the box)
- all inputs need to be wrapped in forwardRef and we also needed to make our own register wrapper in order to pass all needed data easily but the wrapper is unclear and typed in a complicated way
- no out of the box handling for checkboxes and selects
- context is so so, it can be used form wise bo no direct nice way to use it on a field level
- has bugs with accessing nested state that are [treated as features](https://github.com/react-hook-form/react-hook-form/issues/1859) 🙃
- not very graceful treating of submission and methods (mode and a bit mysterious handle submit)

We're also now keeping some stuff in a top level useForm which seems to be a mistake because it's not exactly form state, more app state. Hence the decision is to:
- add Zustand for keeping our simple state stuff, it's lighweight and easy to use 
- replace react-hook-form with Formik which should solve the problems mentioned above
Moreover, using the two above we want to:
- remove the top level form and instead add only a simple state for mutations statuses etc.
- use formik contexed forms for shipping, billing, delivery etc. forms
- move all the forms validation to forms themselves, when clicking pay only pass on a prop via state to trigger their validation and pass a success or failed status back in order to use some common util to show a proper alert

**Comment by bmigirl** [comment]
Closing this, opened a proper [ticket](https://github.com/saleor/react-storefront/issues/627) in the board
