### ISSUE TITLE
Storefront empty cart view error 

### ISSUE THREAD

**Issue by szczecha** [saleor/react-storefront#483]
### Summary

Open empty cart
![image](https://user-images.githubusercontent.com/30683248/191449084-81df72ef-fd1e-4d77-9f76-54b624226e6f.png)

Expected result:
The nice message e.g. your basket is empty should be displayed 

### Steps to reproduce

1. Open cart without any products inside 
2. https://demo.saleor.io/default-channel/en-US/cart/

**Comment by szczecha** [comment]
When testing fix please check following scenario:

**Checkout token is not cleared after changing channel**
Steps to reproduce the problem:
Go to channel-pln  and add item to cart
Change channel in URL to default-channel  and view cart again

Current result:
Checkout remains on the channel-pln  instead of being cleared for default-channel 

Expected result:
Checkout is cleared after changing channel
OR
Checkout is saved per-channel (going back to channel-pln  would restore the old checkout)

**Comment by jTiKey** [comment]
seems they removed the cart completely:
https://github.com/saleor/react-storefront/pull/508

**Comment by timuric** [comment]
@jTiKey checkout gives the same functionality as the cart view, you can adjust quantities and add promo codes. 

We will add mini cart instead in the future.
