### ISSUE TITLE
Fix the checkout container alignment

### ISSUE THREAD

**Issue by zaiste** [saleor/react-storefront#52]
The alignment of elements between the nav bar, the main component and the right side menu is incorrect as shown in the image below:
![CleanShot 2021-10-27 at 14 09 34](https://user-images.githubusercontent.com/200613/139062988-8165f58e-bb39-4791-ac48-9f774b68f5a8.png)
i

**Comment by krzysztofwolski** [comment]
Issue is resolved 
![image](https://user-images.githubusercontent.com/5188636/140100561-5516e3eb-0bb1-4275-b21b-40735959b2ce.png)
