### ISSUE TITLE
Order confirmation page is not loading

### ISSUE THREAD

**Issue by szczecha** [saleor/react-storefront#545]
### Summary

https://staging-demo.saleor.io/checkout/?order=T3JkZXI6MGQwOWJiMTAtZWJhZi00ZWNlLTk5ZDgtZmI3MzM1MjUxNTQ0 

<img width="583" alt="Zrzut ekranu 2022-10-19 o 07 31 07" src="https://user-images.githubusercontent.com/30683248/196637032-3411565e-7107-4877-8cfb-18f6d384733c.png">
Missing &locale=en-US. We should add a default one when it's missing.

### Steps to reproduce

1. Create checkout
2. Fill the form
3. Select dumy payment 
4. Pay for the order 

After payment users is redirected to https://staging-demo.saleor.io/checkout/?order=T3JkZXI6MGQwOWJiMTAtZWJhZi00ZWNlLTk5ZDgtZmI3MzM1MjUxNTQ0 
and see 'We couldn’t fetch information about your checkout. Go back to the store and try again.'

**Comment by bmigirl** [comment]
Fixed, closing
