### ISSUE TITLE
Rethink payment providers and methods configuration

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#564]
# The current state of things
Configuration of Payment Methods is done per channel:
![1](https://user-images.githubusercontent.com/1338731/197007321-eb701cad-71aa-4d55-a2b3-9875e9e67819.png)

Payments are grouped by Payment Methods: Credit Card, Apple Pay, and PayPal. They’re hardcoded. When you expand a payment method, you see all available Payment Providers:
![2](https://user-images.githubusercontent.com/1338731/197007330-4dd65932-429b-4e8d-a5c7-fc5fef853cde.png)

By clicking the small cog icon in the top right corner, you get to Payment Provider settings where you need to input the credentials:
![3](https://user-images.githubusercontent.com/1338731/197007340-8bef5495-7a5f-459d-a846-f12255822667.png)

# Problems

1. This is confusing because you see “Stripe” under “PayPal” even though Stripe doesn’t support PayPal. Currently, there’s no way to hide it.
2. Moreover, you can select a Payment Provider even if you didn’t provide its credentials.
3. Furthermore, the UI suggests you could enable multiple Payment Providers per Payment Method but currently, that’s not the case. i.e. you can only have one Credit Card provider.
4. Enabling a Payment Provider and setting its credentials – two separate views, easy to forget to add the credentials.
5. Payments in Checkout are also confusing. We have the Adyen Dropin component and below we have 3 payment methods to choose from and another "Pay" button. This is confusing.

# Goals
- [ ] Make it more difficult to make mistakes – i.e. impossible to enable payment providers without credentials
- [ ] Make it less confusing – dynamic payment methods per provider instead of a hardcoded list so that I cannot enable Stripe under PayPal.
- [ ] Make it possible to use different providers for different payment methods. For example, I’ve negotiated lower Credit Card fees from Adyen so I use Adyen just for credit cards and Stripe fo Apple Pay and BLIK.
- [ ] Have only a single "Pay" button in Checkout

**Comment by mmiszy** [comment]
Internal doc for reference: https://docs.google.com/document/d/1-NTCfFVob5CsVgHeqiraW5L_EQwZPM0ZC96ax2ViKnM/edit?usp=sharing

**Comment by mmiszy** [comment]
https://github.com/saleor/react-storefront/discussions/618

**Comment by witoszekdev** [comment]
This issue is no longer relevant: we're replacing payment handling in `saleor-app-checkout` in favor of separate Payment Provider Apps ([Changes description](https://github.com/saleor/saleor/issues/11258)).

This configuration will be soon removed: https://github.com/saleor/react-storefront/issues/809
