### ISSUE TITLE
Unable to configure payment gateway

### ISSUE THREAD

**Issue by ashishkpaul** [saleor/react-storefront#566]
### Summary

hello sir, I host and pass nginx proxy react-storefront:3000 and saleor-app-checkout:3001 on two different subdomain respectively. Both are working but in a saleor-dashboard i am unable to configure payment gateway. Getting an error 
```dashboard.5d80776fede891bce276.js?be297ff5ee0ee0bed80e:7728 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://saleor-app-checkout.lan') does not match the recipient window's origin ('https://saleor-dashboard.lan').```

Versions:
dashboard v3.7.9
core v3.7.22
![saleor-Screenshot_2022-10-20_21-14-28](https://user-images.githubusercontent.com/16308863/196999506-e0778344-7918-45ba-bc26-3897bb5feef7.png)

### Steps to reproduce

1. Go to "dashboard v3.7.9"
2. Click On "Apps"
3. Click On "Third Party Apps"
4. Check On Installed payment "Checkout" app
5. Check the errors in a browser console as shown in figure above

### A link to a reproduction repository

https://github.com/saleor/saleor-dashboard

## System:
 - OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
 - CPU: (4) arm64 Neoverse-N1
 - Memory: 21.39 GB / 23.43 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
 - npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
 - pnpm 7.13.4

**Comment by mmiszy** [comment]
Thank you for reporting the problem!
Does the error prevent you from configuring the app?

**Comment by ashishkpaul** [comment]
Yes Sir Its preventing to configring the app. Settings are not saved

![Saleor-Screenshot_2022-10-21_11-49-15](https://user-images.githubusercontent.com/16308863/197126464-6d101613-73f5-490b-9dd7-4934a740cc1c.png)

**Comment by mmiszy** [comment]
These console errors are unrelated to the problem. Can you go to the Network tab in devtools and check which request is returning 500 error for you?

**Comment by ashishkpaul** [comment]
Thanks for reply sir
**500 Error** https://app-checkout.dingpack.com/api/payment-provider-settings/ 
Okay sir, Can u guide me on configuring part
My storefront is running at storefront.example.com from root of the project and app checkout saleor-app-checkout.lan running from /project-root/apps/saleor-app-checkout
On strapi dev console i configured webhook as saleor-app-checkout.lan/api/webhooks/stripe, i dont know where i am doing the mistake

**Comment by ashishkpaul** [comment]
might be nginx is blocking
My config file as
upstream app_checkout
{
        server localhost:3001;
        keepalive 64;
}

server 
{
    server_name app-checkout.dingpack.com;
    error_log   /var/log/nginx/app-checkout-dingpack-com.error.log;
    root /var/www/html/saleor/react-storefront/apps/saleor-app-checkout;

    location /
        {
                include /etc/nginx/snippets/cors-wildcard.conf;
                proxy_pass http://app_checkout/;
                proxy_set_header    Host                $host;
                proxy_set_header    X-Real-IP           $remote_addr;
                proxy_set_header    X-Forwarded-Host    $host;
                proxy_set_header    X-Forwarded-Server  $host;
                proxy_set_header    X-Forwarded-Proto   $scheme;
                proxy_set_header    X-Forwarded-For     $remote_addr;
                proxy_redirect off;
                proxy_connect_timeout 90s;
                proxy_read_timeout 90s;
                proxy_send_timeout 90s;
        }                     


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/app-checkout.dingpack.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/app-checkout.dingpack.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server 
{
    if ($host = app-checkout.dingpack.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name app-checkout.dingpack.com;
    listen 80;
    return 404; # managed by Certbot
}

**Comment by ashishkpaul** [comment]
and same config file for storefront running at storefront.dingpack.com

**Comment by ashishkpaul** [comment]
![saleor-Screenshot_2022-10-21_14-31-29](https://user-images.githubusercontent.com/16308863/197157475-35316607-b385-473e-8cbd-86f829c0d7e1.png)

**Comment by ashishkpaul** [comment]
no other end point is falling except https://app-checkout.dingpack.com/api/payment-provider-settings/

**Comment by mmiszy** [comment]
What's the response body?
Do you see any error logs where you're running app-checkout?

**Comment by ashishkpaul** [comment]
Yes Sir, There are some error logs
**Error Log On Saleor Core** (nginx or pm2) 
tail -f ~/.pm2/logs/djnago-with-pm2-error-2.log
```
2022/10/21 16:46:53 [error] 2146#2146: *660 access forbidden by rule, client: 152.67.1.40, server: lcosapi.dingpack.com, request: "GET /.well-known/jwks.json HTTP/1.1", host: "lcosapi.dingpack.com"
```
**Error Log On Saleor Storefront** (nginx or pm2)
No error log found for 

**Error Log On Saleor App Checkout** (nginx or pm2)
```
2022/10/21 16:43:32 [crit] 8008#8008: *63 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 80.82.77.33, server: 0.0.0.0:443

```
**Error Log On Saleor Dashboard** (nginx or pm2)

```
2022/10/21 16:46:50 [error] 8008#8008: *4 open() "/var/www/html/saleor/dashboard/dash-3-7-9/sw.js.map" failed (2: No such file or directory), client: 223.178.211.241, server: seller.dingpack.com, request: "GET /sw.js.map HTTP/2.0", host: "seller.dingpack.com"
```

**Comment by ashishkpaul** [comment]
Gm, Happy Diwali, Any rewiew or update on this sir?

**Comment by mmiszy** [comment]
As you can see in the first log, there's `access forbidden by rule` error for the `GET /.well-known/jwks.json`.
It's not something we can help you with as it's unrelated to the codebase in this repository – the underlying cause is likely a misconfiguration of your server.

We make available Docker images that you might find useful: https://github.com/saleor/saleor-platform

**Comment by ashishkpaul** [comment]
Hello sir, i still strugling to configure payment gateway through dashboard --> apps
**ReactStorefront** console output
```
saleor-app-checkout:start: JwksError: Forbidden
saleor-app-checkout:start:     at JwksClient.getKeys (/var/www/html/saleor/react-storefront/node_modules/.pnpm/jwks-rsa@2.1.5/node_modules/jwks-rsa/src/JwksClient.js:48:25)
saleor-app-checkout:start:     at runMicrotasks (<anonymous>)
saleor-app-checkout:start:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
saleor-app-checkout:start:     at async JwksClient.getSigningKeys (/var/www/html/saleor/react-storefront/node_modules/.pnpm/jwks-rsa@2.1.5/node_modules/jwks-rsa/src/JwksClient.js:53:18)
saleor-app-checkout:start:     at async JwksClient.getSigningKey (/var/www/html/saleor/react-storefront/node_modules/.pnpm/jwks-rsa@2.1.5/node_modules/jwks-rsa/src/JwksClient.js:71:18)

```
**Google Chrome** console output
![Screenshot_2022-12-02_20-22-40](https://user-images.githubusercontent.com/16308863/205320538-b7ffdeee-cbf3-4e38-9a06-c25117ae7205.png)

Please guide me sir

**Comment by ashishkpaul** [comment]
it's done sir by configuring redis and celery
