### ISSUE TITLE
Hydration error

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#589]
### Summary

Hydration error is visible when `saleor-app-checkout` is loaded in iframe in development

<img width="991" alt="CleanShot 2022-10-26 at 17 27 51@2x" src="https://user-images.githubusercontent.com/4144459/198068856-19dc0874-8654-4ab2-b70f-ca83ab6374bf.png">

### Steps to reproduce

1. Start local Saleor instance using `saleor-platform`: `docker-compose up api`
2. Install app in Saleor which uses tunnel
3. Visit app configuration page

**Comment by dxrvip** [comment]
I have the same problem, have you solved it?
