### ISSUE TITLE
Docker: reduce size of images

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#591]
Reduce the size of docker images produced in `react-storefront` repository by utilizing Next.js standalone mode.

Issues with standalone mode described in this PR: https://github.com/saleor/react-storefront/pull/528#issue-1407577484

Links for further research:
- https://nextjs.org/docs/messages/sharp-missing-in-production

**Comment by virogenesis** [comment]
@witoszekdev hi, I see that this issue got stale, just wondering if there is any progress with reducing the size of the docker image for storefront, and if anyone else has this issue?
