### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#599]
When opening the Checkout app in the dashboard, the following error can be observed in the console.

**Comment by lephuongbg** [comment]
That is due to the checkout's app iframe is not yet loaded. Though the dashboard should have wait for an iframe to be loaded to start sending messages to it.

Similar issue:
https://github.com/davidjbradshaw/iframe-resizer/issues/282#issuecomment-151847781
