### ISSUE TITLE
Add link to return to storefront from checkout

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#619]
Add a buton in order confirmation that allows customers to return to storefront from checkout page.

![Image](https://user-images.githubusercontent.com/4144459/202146096-419b921a-dd69-4743-a275-a2aa3b6796ff.png)

We need to have a way of tracking which storefront redirected to checkout so that later on we can redirect back (we want to have checkout that can support more than 1 storefront)

Possible solutions:
- use the referer header and store it in checkout metadata
- require a query param in URL with storefront URL and read that
- just go back 2 pages (order confirmation, checkout) so that you end up whenever you were before

**Comment by mmiszy** [comment]
I suggest using a query param. We are passing one for graphql endpoint anyway (in the multi tenant pr, soon to be merged) so we can as well add one more :)

Other solutions seem a bit risky to me - you never know if you land where the user intended.
