### ISSUE TITLE
Replace react-hook-form with Formik

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#627]
Discussion and chosen approach [here](https://github.com/saleor/react-storefront/issues/475)

**Comment by szczecha** [comment]
1. a different way to show users about the empty field 

<img width="429" alt="Screenshot 2023-02-02 at 09 55 56" src="https://user-images.githubusercontent.com/30683248/216279750-51929a45-8325-4d24-8353-b65f25ec22f5.png">
<img width="439" alt="Screenshot 2023-02-02 at 10 01 56" src="https://user-images.githubusercontent.com/30683248/216279765-a34bd050-645f-4fb7-9afc-000fad605526.png">


2. unnecessary "0" 
<img width="448" alt="Screenshot 2023-02-02 at 09 57 16" src="https://user-images.githubusercontent.com/30683248/216279793-e315a2fa-2439-46cb-be41-8794ba3442b8.png">

4. Missing notification when trying to complete checkout without email. Before there was notification 'Please fill in email before finalizing checkout'
<img width="439" alt="Screenshot 2023-02-02 at 10 01 56" src="https://user-images.githubusercontent.com/30683248/216279973-837b82d3-100b-4307-a0e3-e3d04d787277.png">

5. The email field is no longer shareable between guest and login forms. Before when I entered my email on guest checkout and then clicked on sign in the email was already filled in in sign in form

**Comment by szczecha** [comment]
6. Different notification for an inactive account before was: 'Account with provided email is inactive' now is: 
<img width="1643" alt="Screenshot 2023-02-02 at 10 11 55" src="https://user-images.githubusercontent.com/30683248/216281579-57fc37bf-2fd1-4afa-8272-be518b789818.png">

7. Missing * in the phone number - without providing phone checkoutShippingAddressUpdate is not sent
8. Checkbox `Use shipping as billing address` does not always work 

Steps:
1. Create new checkout 
2. enter page https://saleor-app-checkout-git-replace-hook-form-3168a4-saleorcommerce.vercel.app/checkout-spa/?locale=en-US&channel=default-channel&domain=master.staging.saleor.cloud&saleorApiUrl=https://master.staging.saleor.cloud/graphql/&checkout={{generatedCheckoutID}}
3. fill out the form 
4. Try to click pay 
Result: Nothing happened, but when I uncheck `Use shipping as billing address` I see that all required fields are highlighted even when the checkout query return billing address values the same as shipping values. 
When I fill billing address or refresh the page I can proceed with the payment

**Comment by szczecha** [comment]
9. Unable to create an account on checkout 

Steps:
1. Enter URL https://saleor-app-checkout-git-replace-hook-form-3168a4-saleorcommerce.vercel.app/checkout-spa/?locale=en-US&channel=default-channel&domain=master.staging.saleor.cloud&saleorApiUrl=https://master.staging.saleor.cloud/graphql/&checkout=Q2hlY2tvdXQ6ZDAzMWFlMjctNzI4MC00MjJiLThhNGItNTc5MGIwMjliNWU3
2. Select I want to create account and fill the password 
3. Click the pay 
Result: Pay button hangs on Processing... No request is sent

**Comment by szczecha** [comment]
10. Missing validation that password is required when checkbox 'I want to create an account' is checked 

https://user-images.githubusercontent.com/30683248/216301199-928ac987-f685-4627-9034-ecdecdde5a6e.mov

**Comment by szczecha** [comment]
11. After resetting the password email should be displayed in the Account section 
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/30683248/216313849-298f5656-3ba9-4e9b-ae4b-761f1a3d341c.png">

**Comment by szczecha** [comment]
13. Removing shippable products from mixed checkout (digital and shipping products)
Result: billing address form is missing 

https://user-images.githubusercontent.com/30683248/216319637-a2740a54-247f-40f4-875b-dd21e33f72c4.mov
