### ISSUE TITLE
saleor-checkout missing credit card form

### ISSUE THREAD

**Issue by matteius** [saleor/react-storefront#630]
### Summary

I finally was able to get the SPA running and configured today for saleor-checkout, however I can place orders, there seems to be no way to pay for them.
![image](https://user-images.githubusercontent.com/479892/202872188-ce44b9ee-d502-43a5-a6b4-9e1c2e7aee6d.png)

### Steps to reproduce

Latest Canary -- Follow the steps to setup everything and add the SPA in the dashboard and configure it.

**Comment by mmiszy** [comment]
Can you elaborate on the problem? What do you mean by "no way to pay"? I can see payment methods and "pay" button in the screen shot. Do you get any errors when you click on it?

**Comment by matteius** [comment]
@mmiszy There is no credit card form regardless of the payment method -- I can click the pay button a checkout that is not paid for, and the subsequent button to pay does nothing.

**Comment by mmiszy** [comment]
What subsequent pay button?

Can you produce a full reproduction, including steps and description?

**Comment by matteius** [comment]
1. Add to card
2. Go to the saleor-checkout-app with said card
3. See the image where there is no credit card form.
![image](https://user-images.githubusercontent.com/479892/202873666-0cdf9bef-a6e0-4d67-a4bc-429f98c28f16.png)

4. Click Pay
5. See this page and get an E-mail that appears like you already paid:

![image](https://user-images.githubusercontent.com/479892/202873672-142491b6-470d-420f-ab72-820b927981f5.png)

6. Click the pay for order button which gets a 500 button because no stirpe webhook secret, but that was never required before.
7. Grep the code base for cardnum and see there is no form field for credit card number.

I am asking about if the credit card form even exists?

**Comment by matteius** [comment]
Ok I just figured out that if I add a webhook URL that it uses the stripe checkout website -- that is fine, but are there plans to add a credit card form as an alternative?

**Comment by matteius** [comment]
Is there a way to have the stripe checkout not auto-capture the payment?

**Comment by wackyesolution** [comment]
same problem, i don't understand something maybe?
