### ISSUE TITLE
Checkout-app is not fetching channels

### ISSUE THREAD

**Issue by mmiszy** [saleor/react-storefront#651]
It looks like https://github.com/saleor/react-storefront/commit/1134c729316f5d1e1c5519fce324ca2225178c59 broke appBridge integration and `isAuthorized` is never set to `true`.

**Comment by matteius** [comment]
Thanks for fixing this -- I will try it this weekend.  This is what I was referring to; I must have had something cached when it was "still working" again, but later that day I couldn't get it to work any longer and switched back to an older commit.
