### ISSUE TITLE
ERROR error: unknown option `initial-branch'

### ISSUE THREAD

**Issue by fenghuilee** [saleor/react-storefront#689]
### Summary

⠇ Setting up the Git repository...
 ERROR error: unknown option `initial-branch'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    --object-format <hash>
                          specify the hash algorithm to use

 If you think this is a bug, report it on GitHub:
 https://github.com/saleor/saleor-cli/issues

 CLI Docs:
 https://docs.saleor.io/docs/3.x/cli

### Steps to reproduce

saleor storefront create front

**Comment by mmiszy** [comment]
Make sure you're using `git` version `2.28.0` or later.
