### ISSUE TITLE
Dummy payment button is not working 

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/react-storefront#699]
### Summary

As an unlogged user I want to use dummy payment ex. on 

[https://react-storefront-e2e.vercel.app/checkout/?checkout=Q2hlY2tvdXQ6NmNiNTk2YzctMGFiMi00MzkxLTg2YjktMTg2YTUzMGEyODJl&locale=en-US&channel=default-channel&saleorApiUrl=https%3A%2F%2Fstorefront-automation.staging.saleor.cloud%2Fgraphql%2F&domain=storefront-automation.staging.saleor.cloud](https://react-storefront-e2e.vercel.app/checkout/?checkout=Q2hlY2tvdXQ6NmNiNTk2YzctMGFiMi00MzkxLTg2YjktMTg2YTUzMGEyODJl&locale=en-US&channel=default-channel&saleorApiUrl=https%3A%2F%2Fstorefront-automation.staging.saleor.cloud%2Fgraphql%2F&domain=storefront-automation.staging.saleor.cloud)

 Environment , when I click on `dummy` button nothing happened. Because of this the test should buy a product as anonymous SRS_1001 is failing

### Steps to reproduce

1. As a unlogged user go to checkout
2. Fill up all required fields
3. Try to click on `dummy` button
![image](https://user-images.githubusercontent.com/25908728/212669821-d2cf7eb4-52a1-4abf-94c1-23148fd9f2cc.png)

Current result: Nothing happened after clicking

**Comment by mmiszy** [comment]
I've investigated, and I confirm there's a bug. Hopefully, it'll be fixed via https://github.com/saleor/react-storefront/pull/679

**Comment by hqlinh796** [comment]
hi @mmiszy , I have met a bug related to above button. When I click to choose Dummy provider (or maybe Dummy method), I saw that `setPaymentData` function was trigger (It set payment method and payment provider to "Dummy" value).  But when I click pay button, the payment method and payment provider still be null.
