### ISSUE TITLE
Root .env.local is not loaded correctly

### ISSUE THREAD

**Issue by tiendq** [saleor/react-storefront#703]
### Summary

Add `SALEOR_API_URL=https://tientest1.saleor.cloud/graphql/` in `.env.local` but storefront is still running with default `SALEOR_API_URL=https://master.staging.saleor.cloud/graphql/` in `.env`. If I change `SALEOR_API_URL` in `.env` directly then it works.

Ref: https://github.com/saleor/react-storefront/blob/canary/docs/faq.md#in-nextjs

### Steps to reproduce

1. Set `SALEOR_API_URL=https://tientest1.saleor.cloud/graphql/` in `.env.local`
2. `pnpm dev`

### Output from envinfo

`pnpm --version`
7.18.2

**Comment by zanami** [comment]
My guess it's here

`"dev": "env-cmd --no-override -f .env env-cmd --no-override  -f .env.local --fallback pnpm run _dev"`

So whatever is defined in .env will **not** be overridden with what is in .env.local

`--no-override  Do not override existing environment variables`

Edit .env as I did or edit package.json to remove --no-override from env-cmd **--no-override**  -f .env.local
