### ISSUE TITLE
checkout-fully-paid webhook

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#730]
This webhook should be triggered when: `checkout.balance == 0`

**Comment by korycins** [comment]
@witoszekdev  There is `checkout-fully-paid` webhook that we delivered in https://github.com/saleor/saleor/pull/12179. Does it mean that this task should be closed, or there is something missing? The PR with the webhook: https://github.com/saleor/saleor/pull/12320

**Comment by mmiszy** [comment]
Fixed in https://github.com/saleor/saleor/pull/12320
