### ISSUE TITLE
Checkout page does not work!!! Can not focus on sales and marketing.

### ISSUE THREAD

**Issue by Sarowar-neo** [saleor/react-storefront#761]
### Summary

Can not add billing address and next steps. 

Localhost demo vs saleor demo.... 

![Screenshot from 2023-03-01 14-34-51](https://user-images.githubusercontent.com/22500875/222086747-7ffce81b-5bea-4b17-95d0-5e8c852ade52.png)
**vs** 
![Screenshot from 2023-03-01 14-35-13](https://user-images.githubusercontent.com/22500875/222086756-723eefc7-88ae-4691-a751-bd10a112bad0.png)

### Steps to reproduce

***

### Output from envinfo

***

**Comment by mmiszy** [comment]
It looks like you're using outdated or modified version of react-storefront.
Please fill in specific steps to reproduce and provide a link to the repository.
