### ISSUE TITLE
Store type of payment method used in transaction in Saleor

### ISSUE THREAD

**Issue by witoszekdev** [saleor/react-storefront#787]
We would like to store payment method user used in payment provider in Saleors' transactions (e.g. credit card / Klarna / Blik).

Previously, we had a `type` field on `Transaction`. Right now we don't have such field.

We could extend this more by adding more data for payment method type - e.g. translatable name, icon, supported currencies, etc. which could be displayed in Payment Apps list in Dashboard.

**Comment by mmiszy** [comment]
I believe this issue belongs to https://github.com/saleor/saleor
