### ISSUE TITLE
Checkout: auto redirect to storefrontURL/checkout-spa/checkout=xxx

### ISSUE THREAD

**Issue by hqlinh796** [saleor/react-storefront#795]
### Summary

I have deployed saleor-app-checkout app and storefront app which followed by the instruction. But when I clicked on the checkout button, the issue came. instead of open storefront/checkout/?checkout=xxx, it opened storefront/checkout-spa/checkout=xxx. And then show not found page.
If i take params from the url and join to checkout-app/checkout-spa/?checkout=xxx, It will be OK.

### Steps to reproduce

1. Add products to cart
2. Click the checkout button
3. Browser will open storefront/checkout-spa/?checkout=xxx

**Comment by mmiszy** [comment]
We cannot reproduce this issue. I think it likely results from a misconfiguration. Can you provide more details or a link to an environment?

**Comment by maektwain** [comment]
I think this is something to do with the production and env variables or something ? I am also facing the same issue here at this https://shop.cicilabel.com , my checkout url application is this https://checkout.cicilabel.com

I am also facing the same issue , where the page ends up on 404 maybe some config or env variable issues

**Comment by maektwain** [comment]
Now, after changing the .env to something else , I was able to get the too many redirects error : `https://shop.cicilabel.com/checkout/?checkout=Q2hlY2tvdXQ6NTI2NzFlMzYtNDA5OC00MzAyLWJiNjAtNzA1ZTgyYjA2ZWNj&locale=en-US&channel=default-channel&domain=cici-label.herokuapp.com&saleorApiUrl=https%3A%2F%2Fcici-label.herokuapp.com%2Fgraphql%2F`

**Comment by mmiszy** [comment]
Closing due to lack of minimal reproducible example.
