### ISSUE TITLE
Redirects Login page after refresh page in AccountLayout Pages

### ISSUE THREAD

**Issue by tayfuncakir** [saleor/react-storefront#815]
### Summary

When refresh the page, the loader does not appear because authenticating was false on initial. At the same time, it is redirected to the login page because it cannot be authenticated.

### Steps to reproduce

1- Login to your account with https://demo.saleor.io/. 
2- click to https://demo.saleor.io/default-channel/en-US/account/preferences/
3- refresh the page

 It will send you to the login page. In addition, the refresh will not be fully performed, half of the page will remain on the account page and half on the login page below.

**Comment by Jyrno42** [comment]
Probably relates to this https://github.com/saleor/react-storefront/issues/790

**Comment by mmiszy** [comment]
Please, provide a minimal reproducible example.
