### ISSUE TITLE
Storefront rewrites misconfigured

### ISSUE THREAD

**Issue by zanami** [saleor/react-storefront#816]
### Summary

These [rewrites](https://github.com/saleor/react-storefront/blob/canary/apps/storefront/next.config.js#L76) do not play well with [trailingSlash: true](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewriting-to-an-external-url)

> If you're using trailingSlash: true, you also need to insert a trailing slash in the source parameter. If the destination server is also expecting a trailing slash it should be included in the destination parameter as well.

```
      {
        source: "/api/manifest",
        destination: `${process.env.NEXT_PUBLIC_CHECKOUT_APP_URL}/api/manifest`,
      },
      {
        source: "/api/install",
        destination: `${process.env.NEXT_PUBLIC_CHECKOUT_APP_URL}/api/install`,
      },
```

### Steps to reproduce

Go to https://yourstorefronturl/api/manifest
Get redirected to https://yourstorefrontulr/api/manifest/
Endless loop here

**Comment by mmiszy** [comment]
Please, provide a minimal reproducible example.
