### ISSUE TITLE
Timing issue causing weird behavior w.r.t locale/channel in url

### ISSUE THREAD

**Issue by Jyrno42** [saleor/react-storefront#824]
### Summary

In a lot of places the router parameters are read as if they are always available, but in client side they may not be resolved during initial rendering flow.

> isReady: boolean - Whether the router fields are updated client-side and ready for use. Should only be used inside of useEffect methods and not for conditionally rendering on the server. See related docs for use case with [automatically statically optimized pages](https://nextjs.org/docs/advanced-features/automatic-static-optimization)

This issue can for example be seen in AccountLayout, where the redirect to the login page is done without checking `isReady`. 

https://github.com/saleor/react-storefront/blob/canary/apps/storefront/components/AccountLayout/AccountLayout.tsx#L27

Since the `router.isReady` is not checked there then once a user navigates to https://demo.saleor.io/default-channel/en-US/account/orders/ without being logged in beforehand then the automatically assigned redirect url in the `next` parameter is not 
properly created and is:

`https://demo.saleor.io/default-channel/en-US/account/login/?next=%2F%5Bchannel%5D%2F%5Blocale%5D%2Faccount%2Forders`

![image](https://user-images.githubusercontent.com/235804/233680857-55436227-03a9-4dd9-be21-a9b627d3fe52.png)

when it should be 

`https://demo.saleor.io/default-channel/en-US/account/login/?next=%2Fdefault-channe%2Fen-US%2Faccount%2Forders`

This particular case is easy to solve, quick fix is to just wrap `void router.push` call in an `if router.isReady` check or alternatively add an useEffect there that handles the clientside redirection logic. 

However there are other places in code where the query parameters are treated as to be always available. For example when visiting https://demo.saleor.io/channel-vi/en-US/ NextJS makes a data call to locales.json with query params as placeholders (`[locale]` and `[channel]`) which results in a 500 error. This one I have not been able to figure out how to fix, since it seems to be related to how useRegions behaves and also only occurs with certain timing conditions.

![image](https://user-images.githubusercontent.com/235804/233682553-96736cfb-bdf1-470f-80ad-1d017a697f36.png)

### Steps to reproduce

included in summary

**Comment by zanami** [comment]
I can confirm
Also sometimes visitors get redirected from https://example.com/ to https://example.com/[channel]/[locale] which causes error 500
